<a href="https://colab.research.google.com/github/ShiaHp/DACS4_RecSystem/blob/main/RCM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movies_data = pd.read_csv('/content/AnimeList.csv',encoding="ISO-8859-1")
movies_data

anime_id                                  title  \
0         11013                          Inu x Boku SS   
1          2104                       Seto no Hanayome   
2          5262                     Shugo Chara!! Doki   
3           721                          Princess Tutu   
4         12365                    Bakuman. 3rd Season   
...         ...                                    ...   
14473     26089             Gutchonpa Omoshiro Hanashi   
14474     21525                   Geba Geba Shou Time!   
14475     37897            Godzilla: Hoshi wo Kuu Mono   
14476     34193  Nippon Mukashibanashi: Sannen Netarou   
14477     37908             Senjou no Valkyria Special   

                   title_english                  title_japanese  \
0      Inu X Boku Secret Service                          ??×?SS   
1          My Bride is a Mermaid                           ?????   
2             Shugo Chara!! Doki                     ???????????   
3                  Princess Tutu                       ?????????   
4                       Bakuman.                           ?????   
...                          ...                             ...   
14473                        NaN                     ???????????   
14474                        NaN                       ????????!   
14475                        NaN                GODZILLA -?????-   
14476                        NaN                   ?????? ??????   
14477                        NaN  ?????????? Valkyria Chronicles   

                                      title_synonyms  \
0                                    Youko x Boku SS   
1                               The Inland Sea Bride   
2      Shugo Chara Ninenme, Shugo Chara! Second Year   
3                                                NaN   
4                                   Bakuman Season 3   
...                                              ...   
14473                                            NaN   
14474                                            NaN   
14475      Godzilla Part 3, Godzilla: Eater of Stars   
14476                                            NaN   
14477            Senjou no Valkyria Fake Movie Promo   

                                               image_url     type    source  \
0      https://myanimelist.cdn-dena.com/images/anime/...       TV     Manga   
1      https://myanimelist.cdn-dena.com/images/anime/...       TV     Manga   
2      https://myanimelist.cdn-dena.com/images/anime/...       TV     Manga   
3      https://myanimelist.cdn-dena.com/images/anime/...       TV  Original   
4      https://myanimelist.cdn-dena.com/images/anime/...       TV     Manga   
...                                                  ...      ...       ...   
14473  https://myanimelist.cdn-dena.com/images/anime/...       TV   Unknown   
14474  https://myanimelist.cdn-dena.com/images/anime/...      OVA   Unknown   
14475  https://myanimelist.cdn-dena.com/images/anime/...    Movie     Other   
14476  https://myanimelist.cdn-dena.com/images/anime/...      OVA     Other   
14477  https://myanimelist.cdn-dena.com/images/anime/...  Special   Unknown   

       episodes           status  ...    premiered           broadcast  \
0            12  Finished Airing  ...  Winter 2012  Fridays at Unknown   
1            26  Finished Airing  ...  Spring 2007             Unknown   
2            51  Finished Airing  ...    Fall 2008             Unknown   
3            38  Finished Airing  ...  Summer 2002  Fridays at Unknown   
4            25  Finished Airing  ...    Fall 2012             Unknown   
...         ...              ...  ...          ...                 ...   
14473         5  Finished Airing  ...    Fall 1987             Unknown   
14474         1  Finished Airing  ...          NaN                 NaN   
14475         1    Not yet aired  ...          NaN                 NaN   
14476         1  Finished Airing  ...          NaN                 NaN   
14477         1  Finished Airing  ...          NaN       

In [ ]:
movies_data.head()

In [ ]:
movies_data.shape

(14478, 31)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['genre','type','source']
print(selected_features)

['genre', 'type', 'source']


In [ ]:
# replacing the null value with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features
combined_features = movies_data['genre']+ ' '+movies_data['type']+' '+movies_data['source']

In [ ]:
print(combined_features)

0          Comedy, Supernatural, Romance, Shounen TV Manga
1        Comedy, Parody, Romance, School, Shounen TV Manga
2                   Comedy, Magic, School, Shoujo TV Manga
3        Comedy, Drama, Magic, Romance, Fantasy TV Orig...
4                 Comedy, Drama, Romance, Shounen TV Manga
                               ...                        
14473                                      Kids TV Unknown
14474                                   Comedy OVA Unknown
14475       Action, Sci-Fi, Adventure, Fantasy Movie Other
14476                              Fantasy, Kids OVA Other
14477                               Comedy Special Unknown
Length: 14478, dtype: object


In [ ]:

# converting the text data to feature vectors
vectorizer = TfidfVectorizer()


In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors )

In [ ]:
# getting the similarity scores cosine similarity
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.27468459 0.06065405 ... 0.         0.         0.02595345]
 [0.27468459 1.         0.41935861 ... 0.         0.         0.04294028]
 [0.06065405 0.41935861 1.         ... 0.         0.         0.05622685]
 ...
 [0.         0.         0.         ... 1.         0.53337963 0.        ]
 [0.         0.         0.         ... 0.53337963 1.         0.        ]
 [0.02595345 0.04294028 0.05622685 ... 0.         0.         1.        ]]


In [ ]:
# getting the movie name from user
movie_name = input('Enter your favourite movie name: ')

Enter your favourite movie name: tari


In [ ]:
# creating a list with all the movie names given in dataset

list_of_all_titles =movies_data['title'].replace(np.nan, '').tolist()
print(list_of_all_titles)

['Inu x Boku SS', 'Seto no Hanayome', 'Shugo Chara!! Doki', 'Princess Tutu', 'Bakuman. 3rd Season', 'Yume-iro Pâtissière', 'Ultra Maniac', 'Shakugan no Shana II (Second)', 'Nodame Cantabile: Paris-hen', 'Ouran Koukou Host Club', 'Junjou Romantica 2', 'Kaichou wa Maid-sama!', 'Sekaiichi Hatsukoi 2', 'Tonari no Kaibutsu-kun', 'Bleach', 'Chobits', 'Kimi ni Todoke', 'Naruto: Shippuuden', 'Ranma ½', 'Toradora!', 'Bakuman. 2nd Season', 'Gakuen Alice', 'Skip Beat!', 'Chihayafuru 2', 'Shounen Onmyouji', 'Chihayafuru', 'Itazura na Kiss', 'Beelzebub', 'Hanasakeru Seishounen', 'SKET Dance', 'B-gata H-kei', 'Crayon Shin-chan', 'Fruits Basket', 'Saiunkoku Monogatari', 'One Piece', 'Glass no Kamen (2005)', 'Air Gear', 'Saiunkoku Monogatari 2nd Season', 'InuYasha', 'Chu-Bra!!', 'Nodame Cantabile Finale', 'Ghost Hunt', 'Accel World', 'Bakuman.', 'Nodame Cantabile', 'Kamisama Hajimemashita', 'Cardcaptor Sakura', 'Daa! Daa! Daa!', 'Kimi ni Todoke 2nd Season', 'Sekaiichi Hatsukoi', 'Code-E', 'Junjou Roma

In [ ]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['The iDOLM@STER', 'The iDOLM@STER SideM']


In [ ]:
close_match = find_close_match[0]
print(close_match)

The iDOLM@STER


In [ ]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data.title == close_match]['Index'].values[0]
print(index_of_the_movie)

779


In [ ]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.20138320307365248), (1, 0.17171332648503967), (2, 0.18289691874081232), (3, 0.3527160427878869), (4, 0.3999544577516232), (5, 0.10982320454129835), (6, 0.16836992121822125), (7, 0.21256237389160715), (8, 0.3005640715752119), (9, 0.15894175980952024), (10, 0.3034337282227931), (11, 0.189723516364958), (12, 0.3034337282227931), (13, 0.14976277884382505), (14, 0.14713535325357535), (15, 0.28762429685684554), (16, 0.21173504340698063), (17, 0.1243260151863563), (18, 0.13680876830252559), (19, 0.14510951967999292), (20, 0.3999544577516232), (21, 0.15418202384868168), (22, 0.3711052877656975), (23, 0.3674469570490756), (24, 0.06766170025239862), (25, 0.3674469570490756), (26, 0.21378246807476037), (27, 0.15809142595090428), (28, 0.29531676605487356), (29, 0.2308749701088189), (30, 0.14042017002944393), (31, 0.1444046571713229), (32, 0.2775586013920179), (33, 0.28565797694736805), (34, 0.27437986294089023), (35, 0.3352501475810351), (36, 0.17147120631608506), (37, 0.28565797694736805),

In [ ]:
len(similarity_score)

14478

In [ ]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score,key = lambda x:x[1], reverse = True )
print(sorted_similar_movies)


[(779, 1.0), (9766, 1.0), (10961, 1.0), (2032, 0.901097362009702), (2912, 0.901097362009702), (6971, 0.901097362009702), (9336, 0.901097362009702), (2241, 0.8773548727177435), (6595, 0.8773548727177435), (2591, 0.8614663912836054), (2517, 0.8470782835240047), (9078, 0.8470782835240047), (10774, 0.8457520138841349), (12038, 0.8457520138841349), (1399, 0.7876170623313017), (1450, 0.7876170623313017), (7904, 0.7876170623313017), (6692, 0.7727556661566197), (5181, 0.7467751643196319), (1640, 0.7410446435351115), (4355, 0.7410446435351115), (10334, 0.7410446435351115), (207, 0.7338462939729624), (4217, 0.7338462939729624), (4917, 0.7338462939729624), (5146, 0.7338462939729624), (5473, 0.7338462939729624), (7535, 0.7338462939729624), (9136, 0.7338462939729624), (9201, 0.7338462939729624), (11720, 0.7338462939729624), (12419, 0.7338462939729624), (13065, 0.7338462939729624), (14276, 0.7338462939729624), (1584, 0.7012375805955151), (9580, 0.7012375805955151), (11240, 0.6993442230015137), (1319

In [ ]:
# print the name of similar movie based on the index
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.Index == index]['title']
  if (i<30):
      print(i, '.',title_from_index)
      i+=1

 


Movie Recommendation System


In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles =movies_data['title'].replace(np.nan, '').tolist()


find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_match]['Index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.Index == index]['title']
  if (i<30):
      print(i, '.',title_from_index)
      i+=1


 Enter your favourite movie name : naruto
Movies suggested for you: 

1 . 17    Naruto: Shippuuden
Name: title, dtype: object
2 . 4504    Naruto
Name: title, dtype: object
3 . 130    Rekka no Honoo
Name: title, dtype: object
4 . 4960    Boruto: Naruto Next Generations
Name: title, dtype: object
5 . 169    Dragon Ball Super
Name: title, dtype: object
6 . 917    Dragon Ball Z
Name: title, dtype: object
7 . 3626    Dragon Ball Kai (2014)
Name: title, dtype: object
8 . 7897    Dragon Ball Kai
Name: title, dtype: object
9 . 3895    Dragon Ball
Name: title, dtype: object
10 . 9843    Boruto: Jump Festa 2016 Special
Name: title, dtype: object
11 . 5221    Naruto: Honoo no Chuunin Shiken! Naruto vs. Ko...
Name: title, dtype: object
12 . 12149    Naruto: Shippuuden Movie 6 - Road to Ninja
Name: title, dtype: object
13 . 9974    Dragon Ball Z: Atsumare! Gokuu World
Name: title, dtype: object
14 . 3709    Naruto x UT
Name: title, dtype: object
15 . 1773    Dragon Ball Super Movie
Name: title, dty